version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers

    working_directory: ~/repo

    environment:
      APP_ENV: sqlite_memory_testing
      APP_KEY: base64:RbqDAmtaSuDTEd1FGFhPyFjuFYLxRky86U3yfJMabEU=

    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt-get install -y libpng-dev
      - run: sudo docker-php-ext-install gd  zip bcmath
      - run: openssl genrsa -out storage/oauth-private.key 4096
      - run: openssl rsa -in storage/oauth-private.key -pubout > storage/oauth-public.key

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: cp .env.ci .env
      - run: vendor/bin/phpunit
      - store_test_results:
          path: test-results
