<?php

namespace App\Services\GitHub;

use App\Models\Translations\GitConfig;

class GitHubPullRequestService extends GitHubService
{
    private const STANDARD_PULL_REQUEST_MESSAGE_PREFIX = 'Jargon translation sync ';

    /**
     * Creates a pull request from a given branch.
     *
     * @param \App\Models\Translations\GitConfig $gitConfig
     * @param string                             $branch
     *
     * @throws \Github\Exception\MissingArgumentException
     *
     * @return array
     */
    public function createPullRequest(GitConfig $gitConfig, string $branch): array
    {
        return $this->gitHubManager
            ->pullRequests()
            ->create($gitConfig->username, $gitConfig->repository,
                [
                    'title'                 => implode(' ', [self::STANDARD_PULL_REQUEST_MESSAGE_PREFIX, uniqid()]),
                    'body'                  => 'This is an automatic pull request generated by Jargon.',
                    'head'                  => $branch,
                    'base'                  => $gitConfig->base_branch,
                    'maintainer_can_modify' => true,
                ]
            )
        ;
    }

    /**
     * Closes a given pull request.
     *
     * @param \App\Models\Translations\GitConfig $gitConfig
     * @param string                             $prNumber
     *
     * @return array
     */
    public function closePullRequest(GitConfig $gitConfig, string $prNumber): array
    {
        return $this->gitHubManager
            ->pullRequests()
            ->update($gitConfig->username, $gitConfig->repository, $prNumber,
                [
                    'base'   => $gitConfig->base_branch,
                    'status' => 'closed',
                ]
            )
        ;
    }
}
